# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
departments = Department.create ([

{name: "AC", desc: "Accountancy"},
{name: "EC", desc: "Economics and Public Policy"},
{name: "BE", desc: "Entrepreneurship"},
{name: "FM", desc: "Financial Management"},
{name: "HR", desc: "Human Resource"},
{name: "IT", desc: "Information and Communication Technology"},
{name: "LM", desc: "Legal Management"},
{name: "MC", desc: "Marketing and Corporate Communication"},
{name: "OM", desc: "Operations Management"},
{name: "PS", desc: "Psychology"}

	])

sections = Section.create ([

{name: "A", department_id: 1, yearlevel: "1"},
{name: "B", department_id: 1, yearlevel: "1"},
{name: "C", department_id: 1, yearlevel: "1"},
{name: "D", department_id: 1, yearlevel: "1"},
{name: "E", department_id: 1, yearlevel: "1"},
{name: "F", department_id: 1, yearlevel: "1"},
{name: "G", department_id: 1, yearlevel: "1"},
{name: "H", department_id: 1, yearlevel: "1"},
{name: "I", department_id: 1, yearlevel: "1"},
{name: "J", department_id: 1, yearlevel: "1"},
{name: "K", department_id: 1, yearlevel: "1"},
{name: "A", department_id: 2, yearlevel: "1"},
{name: "B", department_id: 2, yearlevel: "1"},
{name: "C", department_id: 2, yearlevel: "1"},
{name: "D", department_id: 2, yearlevel: "1"},
{name: "A", department_id: 3, yearlevel: "1"},
{name: "B", department_id: 3, yearlevel: "1"},
{name: "C", department_id: 3, yearlevel: "1"},
{name: "D", department_id: 3, yearlevel: "1"},
{name: "A", department_id: 4, yearlevel: "1"},
{name: "B", department_id: 4, yearlevel: "1"},
{name: "C", department_id: 4, yearlevel: "1"},
{name: "D", department_id: 4, yearlevel: "1"},
{name: "A", department_id: 5, yearlevel: "1"},
{name: "B", department_id: 5, yearlevel: "1"},
{name: "C", department_id: 5, yearlevel: "1"},
{name: "D", department_id: 5, yearlevel: "1"},
{name: "A", department_id: 6, yearlevel: "1"},
{name: "B", department_id: 6, yearlevel: "1"},
{name: "C", department_id: 6, yearlevel: "1"},
{name: "D", department_id: 6, yearlevel: "1"},
{name: "A", department_id: 7, yearlevel: "1"},
{name: "B", department_id: 7, yearlevel: "1"},
{name: "C", department_id: 7, yearlevel: "1"},
{name: "D", department_id: 7, yearlevel: "1"},
{name: "E", department_id: 7, yearlevel: "1"},
{name: "A", department_id: 8, yearlevel: "1"},
{name: "B", department_id: 8, yearlevel: "1"},
{name: "C", department_id: 8, yearlevel: "1"},
{name: "D", department_id: 8, yearlevel: "1"},
{name: "E", department_id: 8, yearlevel: "1"},
{name: "A", department_id: 9, yearlevel: "1"},
{name: "B", department_id: 9, yearlevel: "1"},
{name: "C", department_id: 9, yearlevel: "1"},
{name: "D", department_id: 9, yearlevel: "1"},
{name: "A", department_id: 10, yearlevel: "1"},
{name: "B", department_id: 10, yearlevel: "1"},
{name: "C", department_id: 10, yearlevel: "1"},
{name: "D", department_id: 10, yearlevel: "1"},
{name: "A", department_id: 1, yearlevel: "2"},
{name: "B", department_id: 1, yearlevel: "2"},
{name: "C", department_id: 1, yearlevel: "2"},
{name: "D", department_id: 1, yearlevel: "2"},
{name: "A", department_id: 2, yearlevel: "2"},
{name: "B", department_id: 2, yearlevel: "2"},
{name: "C", department_id: 2, yearlevel: "2"},
{name: "D", department_id: 2, yearlevel: "2"},
{name: "A", department_id: 3, yearlevel: "2"},
{name: "B", department_id: 3, yearlevel: "2"},
{name: "C", department_id: 3, yearlevel: "2"},
{name: "D", department_id: 3, yearlevel: "2"},
{name: "A", department_id: 4, yearlevel: "2"},
{name: "B", department_id: 4, yearlevel: "2"},
{name: "C", department_id: 4, yearlevel: "2"},
{name: "D", department_id: 4, yearlevel: "2"},
{name: "A", department_id: 5, yearlevel: "2"},
{name: "B", department_id: 5, yearlevel: "2"},
{name: "C", department_id: 5, yearlevel: "2"},
{name: "D", department_id: 5, yearlevel: "2"},
{name: "A", department_id: 6, yearlevel: "2"},
{name: "B", department_id: 6, yearlevel: "2"},
{name: "C", department_id: 6, yearlevel: "2"},
{name: "D", department_id: 6, yearlevel: "2"},
{name: "A", department_id: 7, yearlevel: "2"},
{name: "B", department_id: 7, yearlevel: "2"},
{name: "C", department_id: 7, yearlevel: "2"},
{name: "D", department_id: 7, yearlevel: "2"},
{name: "A", department_id: 8, yearlevel: "2"},
{name: "B", department_id: 8, yearlevel: "2"},
{name: "C", department_id: 8, yearlevel: "2"},
{name: "D", department_id: 8, yearlevel: "2"},
{name: "A", department_id: 9, yearlevel: "2"},
{name: "B", department_id: 9, yearlevel: "2"},
{name: "C", department_id: 9, yearlevel: "2"},
{name: "D", department_id: 9, yearlevel: "2"},
{name: "A", department_id: 10, yearlevel: "2"},
{name: "B", department_id: 10, yearlevel: "2"},
{name: "C", department_id: 10, yearlevel: "2"},
{name: "D", department_id: 10, yearlevel: "2"},
{name: "A", department_id: 1, yearlevel: "3"},
{name: "B", department_id: 1, yearlevel: "3"},
{name: "C", department_id: 1, yearlevel: "3"},
{name: "D", department_id: 1, yearlevel: "3"},
{name: "A", department_id: 2, yearlevel: "3"},
{name: "B", department_id: 2, yearlevel: "3"},
{name: "C", department_id: 2, yearlevel: "3"},
{name: "D", department_id: 2, yearlevel: "3"},
{name: "A", department_id: 3, yearlevel: "3"},
{name: "B", department_id: 3, yearlevel: "3"},
{name: "C", department_id: 3, yearlevel: "3"},
{name: "D", department_id: 3, yearlevel: "3"},
{name: "A", department_id: 4, yearlevel: "3"},
{name: "B", department_id: 4, yearlevel: "3"},
{name: "C", department_id: 4, yearlevel: "3"},
{name: "D", department_id: 4, yearlevel: "3"},
{name: "A", department_id: 5, yearlevel: "3"},
{name: "B", department_id: 5, yearlevel: "3"},
{name: "C", department_id: 5, yearlevel: "3"},
{name: "D", department_id: 5, yearlevel: "3"},
{name: "A", department_id: 6, yearlevel: "3"},
{name: "B", department_id: 6, yearlevel: "3"},
{name: "C", department_id: 6, yearlevel: "3"},
{name: "D", department_id: 6, yearlevel: "3"},
{name: "A", department_id: 7, yearlevel: "3"},
{name: "B", department_id: 7, yearlevel: "3"},
{name: "C", department_id: 7, yearlevel: "3"},
{name: "D", department_id: 7, yearlevel: "3"},
{name: "A", department_id: 8, yearlevel: "3"},
{name: "B", department_id: 8, yearlevel: "3"},
{name: "C", department_id: 8, yearlevel: "3"},
{name: "D", department_id: 8, yearlevel: "3"},
{name: "A", department_id: 9, yearlevel: "3"},
{name: "B", department_id: 9, yearlevel: "3"},
{name: "C", department_id: 9, yearlevel: "3"},
{name: "D", department_id: 9, yearlevel: "3"},
{name: "A", department_id: 10, yearlevel: "3"},
{name: "B", department_id: 10, yearlevel: "3"},
{name: "C", department_id: 10, yearlevel: "3"},
{name: "D", department_id: 10, yearlevel: "3"},
{name: "A", department_id: 1, yearlevel: "4"},
{name: "B", department_id: 1, yearlevel: "4"},
{name: "C", department_id: 1, yearlevel: "4"},
{name: "D", department_id: 1, yearlevel: "4"},
{name: "A", department_id: 2, yearlevel: "4"},
{name: "B", department_id: 2, yearlevel: "4"},
{name: "C", department_id: 2, yearlevel: "4"},
{name: "D", department_id: 2, yearlevel: "4"},
{name: "A", department_id: 3, yearlevel: "4"},
{name: "B", department_id: 3, yearlevel: "4"},
{name: "C", department_id: 3, yearlevel: "4"},
{name: "D", department_id: 3, yearlevel: "4"},
{name: "A", department_id: 4, yearlevel: "4"},
{name: "B", department_id: 4, yearlevel: "4"},
{name: "C", department_id: 4, yearlevel: "4"},
{name: "D", department_id: 4, yearlevel: "4"},
{name: "A", department_id: 5, yearlevel: "4"},
{name: "B", department_id: 5, yearlevel: "4"},
{name: "C", department_id: 5, yearlevel: "4"},
{name: "D", department_id: 5, yearlevel: "4"},
{name: "A", department_id: 6, yearlevel: "4"},
{name: "B", department_id: 6, yearlevel: "4"},
{name: "C", department_id: 6, yearlevel: "4"},
{name: "D", department_id: 6, yearlevel: "4"},
{name: "A", department_id: 7, yearlevel: "4"},
{name: "B", department_id: 7, yearlevel: "4"},
{name: "C", department_id: 7, yearlevel: "4"},
{name: "D", department_id: 7, yearlevel: "4"},
{name: "A", department_id: 8, yearlevel: "4"},
{name: "B", department_id: 8, yearlevel: "4"},
{name: "C", department_id: 8, yearlevel: "4"},
{name: "D", department_id: 8, yearlevel: "4"},
{name: "A", department_id: 9, yearlevel: "4"},
{name: "B", department_id: 9, yearlevel: "4"},
{name: "C", department_id: 9, yearlevel: "4"},
{name: "D", department_id: 9, yearlevel: "4"},
{name: "A", department_id: 10, yearlevel: "4"},
{name: "B", department_id: 10, yearlevel: "4"},
{name: "C", department_id: 10, yearlevel: "4"},
{name: "D", department_id: 10, yearlevel: "4"}

	])



 

professors = Professor.create([
{lname: "ACERO", fname: "Liwayway", mi: "H", status: "FT" },
{lname:"ACHACOSO",fname:"Marc David",mi:"C", status: "FT 3rd Pro" },
{lname:"AGREDA",fname:"Sybil",mi:"L", status: "FT" },
{lname:"ALAJAR",fname:"Joffre",mi:"M", status: "FT Admin" },
{lname:"ALER",fname:"Diosdado III",mi:"M", status: "FT Admin" },
{lname:"AMBION",fname:"Larry",mi:"J", status: "FT" },
{lname:"ANGELES",fname:"Moses Aaron",mi:"T", status: "FT" },
{lname:"ARANTE",fname:"Jonathan", status: "FT 2nd Pro" } ,
{lname:"BALBOA-CAHIG",fname:"Jennifer",mi:"A", status: "FT 2nd Pro Admin" },
{lname:"BATINO",fname:"Lamberto Jr.",mi:"A", status: "FT Admin" },
{lname:"BENGCO",fname:"Ma. Jocelyn",mi:"O", status: "FT Admin" },
{lname:"BERNARDO",fname:"Delilah",mi:"G", status: "FT" },
{lname:"BRANZUELA",fname:"Tita",mi:"E", status: "FT Admin" },
{lname:"BRONOSA",fname:"Charles",mi:"D", status: "FT 2nd Pro" },
{lname:"BUNAG",fname:"Ronald", status: "FT 2nd Pro" },
{lname:"BUSTAMANTE",fname:"Christian Bryan",mi:"S", status: "FT Admin" },
{lname:"BUTAC",fname:"Susan",mi:"R", status: "FT" },
{lname:"CABAYSA",fname:"Carissa",mi:"C", status: "FT" },
{lname:"CAMACHO",fname:"Matt",mi:"D", status: "FT 2nd Pro" },
{lname:"CARANGUIAN",fname:"Rey",mi:"M", status: "FT" },
{lname:"CASTILLO",fname:"Julio", status: "FT 1st Pro" },
{lname:"CASTRO",fname:"Raquel", status: "FT" },
{lname:"CLEMENTE",fname:"Paulo",mi:"B", status: "FT" },
{lname:"CRUZ",fname:"Maria Eliza",mi:"P", status: "FT 2nd Pro" },
{lname:"CUARESMA",fname:"Esther",mi:"R", status: "FT" },
{lname:"CUCIO",fname:"Rita",mi:"R", status: "FT 3rd Pro" },
{lname:"DALUPING",fname:"Rebecca",mi:"C", status: "FT" },
{lname:"DANGO",fname:"Josephine",mi:"C", status: "FT" },
{lname:"DEJESUS",fname:"Socorro",mi:"D", status: "FT" },
{lname:"DEROXAS",fname:"Joseph", status: "FT 2nd Pro" },
{lname:"DIAZ",fname:"Dixie", status: "FT 2nd Pro" },
{lname:"DIMARUCOT",fname:"Heildenberg", status: "FT  2nd Pro" },
{lname:"DONOZO",fname:"Arnold", status: "FT 1st Pro" },
{lname:"DULAY",fname:"Teresita",mi:"B", status: "FT" },
{lname:"ESGUERRA",fname:"Anna Maria",mi:"C", status: "FT" },
{lname:"ESTAFIA",fname:"Luisita",mi:"P", status: "FT" }, 
{lname:"ESTRELLA",fname:"Maria Lani",mi:"S", status: "FT 2nd Pro" },
{lname:"FEBRE",fname:"Francisco Jr.",mi:"A", status: "FT Admin" },
{lname:"FERNANDO",fname:"Araceli",mi:"T", status: "FT Admin" },
{lname:"FONSECA",fname:"Jennifer", status: "FT" },
{lname:"FONSECA",fname:"Jesster",mi:"B", status: "FT" },
{lname:"GABRIEL",fname:"Nancy",mi:"K", status: "FT Admin" },
{lname:"GALANG",fname:"Gary",mi:"M", status: "FT 3rd Pro" },
{lname:"GEMENTIZA",fname:"Rivero", status: "FT 1st Pro" },
{lname:"GUETA",fname:"Maria FeRebecca",mi:"D", status: "FT" },
{lname:"GUIA",fname:"Kim", status: "FT 2nd Pro" },
{lname:"IRINCO-SALINAS",fname:"Reiza",mi:"R", status: "FT" },
{lname:"JIMENEZ",fname:"Ma.Luz",mi:"LM", status: "FT" },
{lname:"JOCSON",fname:"Magdalena",mi:"O", status: "FT" },
{lname:"LEAL",fname:"Melanio",mi:"L", status: "FT Admin" },
{lname:"LUGTU",fname:"Vincent",mi:"E", status: "FT 3rd Pro" },
{lname:"LUNA",fname:"Alden Reuben", status: "FT 3rd Pro" },
{lname:"MACAPAGAL",fname:"Luisito", status: "FT" },
{lname:"MANAHAN",fname:"Antonino Arturo",mi:"C", status: "FT" },
{lname:"MANGUBAT",fname:"Dennis",mi:"DP", status: "FT 2nd Pro" },
{lname:"MARCELINO",fname:"Ramon Benedicto",mi:"N", status: "FT" },
{lname:"MARTINEZ",fname:"Kerwin Mark",mi:"D", status: "FT" },
{lname:"MATITU",fname:"Bayani",mi:"C", status: "FT" },
{lname:"MORENO",fname:"Jackqui",mi:"R", status: "FT Admin" },
{lname:"MUÑEZ",fname:"Jephte",mi:"O", status: "FT 1st Pro" },
{lname:"NATIVIDAD",fname:"Lizel Rose",mi:"Q", status: "FT  2nd Pro" },
{lname:"NIEVA",fname:"Alvin",mi:"M", status: "FT Admin" },
{lname:"OASAN",fname:"Albert",mi:"C", status: "FT" },
{lname:"PACULANAN",fname:"Ronel",mi:"S", status: "FT" },
{lname:"PALABRICA",fname:"Jose Maria",mi:"J", status: "FT 2nd Pro" },
{lname:"PASQUIN",fname:"Eric",mi:"G", status: "FT Admin" },
{lname:"PEREZ",fname:"Renelyn",mi:"G", status: "FT 2nd Pro" },
{lname:"PISCOS",fname:"James Loreto",mi:"C", status: "FT Admin" },
{lname:"PLENO",fname:"Noel Francisco", status: "FT 3rd Pro" },
{lname:"PRUDENTE",fname:"Josephine",mi:"E", status: "FT" },
{lname:"QUILON",fname:"Annabel",mi:"D", status: "FT" },
{lname:"RADA",fname:"Ester",mi:"T", status: "FT" },
{lname:"RAMIREZ",fname:"Neilia",mi:"B", status: "FT" },
{lname:"RAMOS",fname:"Jennifer",mi:"T", status: "FT Admin" },
{lname:"RAMOS",fname:"Pilipino",mi:"A", status: "FT" },
{lname:"REMIGIO",fname:"Candida",mi:"P", status: "FT" },
{lname:"REVILLA",fname:"Nerissa",mi:"M", status: "FT Admin" },
{lname:"REYES",fname:"Marvin",mi:"R", status: "FT Admin" },
{lname:"REYES",fname:"Violeta",mi:"C", status: "FT" },
{lname:"RIVERO",fname:"Rowena",mi:"J", status: "FT" },
{lname:"ROMERO",fname:"Alejandro Jr.",mi:"T", status: "FT" },
{lname:"ROQUE",fname:"Ma. Simplicia", status: "FT 2nd Pro" },
{lname:"RUBIO",fname:"Michael JohnY", status: "FT Admin" },
{lname:"RUZOL",fname:"Hipolito",mi:"S", status: "FT" },
{lname:"SAMPAGA",fname:"Genesis",mi:"L", status: "FT 3rd Pro" },
{lname:"SANCHEZ",fname:"Frederick", status: "FT 2nd Pro" },
{lname:"SANTANA",fname:"Don",mi:"A", status: "FT" },
{lname:"SANTANDER",fname:"Noel",mi:"D", status: "FT" },
{lname:"SANTIAGO",fname:"Rosalinda",mi:"B", status: "FT 3rd Pro" },
{lname:"SANTOS",fname:"Gerard Mark",mi:"C", status: "FT 2nd  Pro" },
{lname:"SANTOS",fname:"Matilde",mi:"M", status: "FT" },
{lname:"SERRANO",fname:"Minerva",mi:"T", status: "FT" },
{lname:"TABLANG",fname:"Joselito",mi:"A", status: "FT Admin" },
{lname:"TENDERO",fname:"Ma. Pamela",mi:"G", status: "FT  2nd Pro Admin" },
{lname:"TIBI",fname:"Elsa",mi:"R", status: "FT 2nd Pro" },
{lname:"TIU",fname:"Catalina",mi:"P", status: "FT" },
{lname:"TUTOR",fname:"Julius",mi:"B", status: "FT 2nd Pro" },
{lname:"TUY",fname:"Fedeliz",mi:"S", status: "FT Admin" },
{lname:"URETA",fname:"Lorisma", status: "FT" },
{lname:"VILORIA",fname:"Rulina",mi:"B", status: "FT Admin" },
{lname:"VIRAY",fname:"EdilbertoJr.",mi:"B", status: "FT" },
{lname:"VIRGINO",fname:"Josephine",mi:"S", status: "FT 3rd Pro" },
{lname:"YU",fname:"Dolores",mi:"N", status: "FT" }

	])



rooms = Room.create([
{
name: "Lab A" }, {
name: "Lab B" }, {
name: "Lab C" }, {
name: "Lab D" }, {
name: "12b" }, {
name: "12c" }, {
name: "12E" }, {
name: "12F" }, {
name: "12G" }, {
name: "12I" }, {
name: "12J" }, {
name: "12K" }, {
name: "12L" }, {
name: "12M" }, {
name: "12Q" }, {
name: "12R" }, {
name: "12S" }, {
name: "12V" }, {
name: "12W" }, {
name: "12X" }, {
name: "12Y" }, {
name: "13B" }, {
name: "13C" }, {
name: "13D" }, {
name: "13E" }, {
name: "13F" }, {
name: "13G" }, {
name: "13H" }, {
name: "13I" }, {
name: "13J" }, {
name: "13K" }, {
name: "13L" }, {
name: "13M" }, {
name: "13O" }, {
name: "13Q" }, {
name: "13R" }, {
name: "13S" }, {
name: "13T" }, {
name: "13W" }, {
name: "13X" }, {
name: "13Y" }, {
name: "33C" }, {
name: "33D" }, {
name: "33E" }, {
name: "33F" }, {
name: "33G" }, {
name: "33H" }, {
name: "33I" }, {
name: "33J" }, {
name: "33K" }, {
name: "33L" }, {
name: "34C" }, {
name: "34D" }, {
name: "34E" }, {
name: "34F" }, {
name: "34G" }, {
name: "34H" }, {
name: "34I" }, {
name: "34J" }, {
name: "34K" }, {
name: "34L" }, {
name: "34M" }, {
name: "34N" }, {
name: "34O" }, {
name: "34P" }, {
name: "41B" }, {
name: "41C" }, {
name: "41D" }, {
name: "41E" }, {
name: "41F" }, {
name: "41G" }, {
name: "41H" }, {
name: "41I" }, {
name: "52A" }, {
name: "53B" }, {
name: "54B" }, {
name: "54C" }, {
name: "52C" }

])

subjects = Subject.create([
{name:"ACC01"	, desc:"Fundamentals of Accounting", units:3},
{name:"ACC02"	, desc:"Partnership and Corporation Accounting", units:3},
{name:"ACC03"	, desc:"Financial Accounting, Part 1", units:3},
{name:"ACC04"	, desc:"Financial Accounting, Part I", units:3},
{name:"ACC05"	, desc:"Theory of Accounts-Financial Accounting and Reporting", units:3},
{name:"ACC06"	, desc:"Advance Accounting Problems, Part I", units:3},
{name:"ACC07"	, desc:"Advance Accounting Problems, Part II", units:3},
{name:"ACC08"	, desc:"Financial Management, Part I", units:3},
{name:"ACC09"	, desc:"Financial Management, Part II", units:3},
{name:"ACC10"	, desc:"Cost Accounting and Cost Management", units:3},
{name:"ACC11"	, desc:"Accounting Office Practicum", units:3},
{name:"ACC12"	, desc:"Auditing and Assurance Service, Part I", units:3},
{name:"ACC13"	, desc:"Auditing Assurance Service Part II", units:3},
{name:"ACC14"	, desc:"Management Accounting, Part I", units:3},
{name:"ACC15"	, desc:"Management Accounting Part II", units:3},
{name:"ACC16"	, desc:"Management Consultancy", units:3},
{name:"ACC17"	, desc:"Accounting Review Workshop I (with Accounting for Governmental, Not-For-Profit Entitles & Specialize Industries)", units:3},
{name:"ACC18"	, desc:"Accounting Information System", units:3},
{name:"ACC18"	, desc:"Fundamentals of Accounting Part II", units:3},
{name:"ACC19"	, desc:"Auditing in a CIS Environment", units:3},
{name:"ACC1A"	, desc:"Fundamentals of Accounting, Part 1", units:3},
{name:"ACC1B"	, desc:"Fundamentals of Accounting, Part 2", units:3},
{name:"ACC1E"	, desc:"Fundamentals of Accounting", units:3},
{name:"ACC2A"	, desc:"Partnership and Corporation Accounting", units:3},
{name:"ACC2E"	, desc:"Financial Accounting", units:3},
{name:"ACC4A"	, desc:"Management Accounting", units:3},
{name:"ACC4C"	, desc:"Management Accounting", units:3},
{name:"ACCF"	, desc:"Financial Accounting for Financial Management Majors", units:3},
{name:"ACCF2"	, desc:"Managerial Accounting for Financial Management majors", units:3},
{name:"ADSTT"	, desc:"Advance Statistics", units:3},
{name:"ARTAP"	, desc:"Art Appreciation", units:3},
{name:"ASCIV"	, desc:"Asian Civilization", units:3},
{name:"ASTAT"	, desc:"Applied Business Statistics", units:3},
{name:"BENE1"	, desc:"St. Benedict and the Holy Rule", units:3},
{name:"BENE2"	, desc:"Selected Topics on the Rule of St. Benedict", units:3},
{name:"BENE3"	, desc:"Benedictine Spirituality and the Corporate World", units:3},
{name:"BFM01"	, desc:"Financial Management", units:3},
{name:"BFM02"	, desc:"Financial Analysis and Reporting", units:3},
{name:"BFM03"	, desc:"Banking and Financial Institution", units:3},
{name:"BFM04"	, desc:"Monetary Policy and Central Banking", units:3},
{name:"BFM05"	, desc:"Investment and Portfolio Management", units:3},
{name:"BFM06"	, desc:"Credit and Collection", units:3},
{name:"BFM07"	, desc:"Capital Markets", units:3},
{name:"BFM08"	, desc:"Strategic Financial Management", units:3},
{name:"BFM09"	, desc:"Special Topics in Financial Management", units:3},
{name:"BIOSC"	, desc:"Biological Science", units:3},
{name:"BLW01"	, desc:"Obligations and Contracts", units:3},
{name:"BLW02"	, desc:"Negotiable Instruments and Other Special Laws", units:3},
{name:"BLW03"	, desc:"Law on Business Organizations", units:3},
{name:"BLW04"	, desc:"Law on Sales, Agencies, Bailment and Credit Transactions", units:3},
{name:"CHEM1"	, desc:"General Chemistry with Laboratory", units:3},
{name:"CHEM2"	, desc:"Organic Chemistry with Laboratory", units:3},
{name:"COMP1"	, desc:"Fundamentals of Computer Software and Application", units:3},
{name:"COMP2"	, desc:"Fundamentals of Programming and Database Theory and Applications", units:3},
{name:"COMP3"	, desc:"Web Page Design and Animation", units:3},
{name:"COMP3A"	, desc:"IT Concepts and System Analysis and Design Development", units:3},
{name:"ECO01"	, desc:"Fundamentals of Economics", units:3},
{name:"ECO02"	, desc:"Macroeconomic Theory", units:3},
{name:"ECO03"	, desc:"Intermediate Microeconomic Theory ", units:3},
{name:"ECO04"	, desc:"Intermediate Macroeconomic Theory", units:3},
{name:"ECO05"	, desc:"Mathematical Economics", units:3},
{name:"ECO06"	, desc:"Econometrics I", units:3},
{name:"ECO07"	, desc:"Econometrics II", units:3},
{name:"ECO08"	, desc:"Development and Policy Economics", units:3},
{name:"ECO09"	, desc:"Monetary Theory and Policy", units:3},
{name:"ECO10"	, desc:"Management Economics", units:3},
{name:"ECO11"	, desc:"Economics of Policy Formulations Analysis andImplementation", units:3},
{name:"ECO12"	, desc:"Development of Economic Ideas", units:3},
{name:"ECO13"	, desc:"Human Resource Economics", units:3},
{name:"ECO14"	, desc:"Investment and Financial Markets", units:3},
{name:"ECO15"	, desc:"Public Economics Expenditures", units:3},
{name:"ECO16"	, desc:"Public Economics Taxation", units:3},
{name:"ECO17"	, desc:"Computer and Data Resource for Economics", units:3},
{name:"ECO18"	, desc:"Economics of Natural Resource and Sustainability", units:3},
{name:"ECO19"	, desc:"Regional and Urban Economics", units:3},
{name:"ECO20"	, desc:"Economic of Law", units:3},
{name:"ECO21"	, desc:"Industrial Organization Theory and Policy", units:3},
{name:"ECO22"	, desc:"International Economics", units:3},
{name:"ECO23"	, desc:"Agro- Industrial Policy Analysis with Project Planning and Evaluation", units:3},
{name:"ECO24"	, desc:"ElectiveHealth EconomicsEconomics of EducationTransportation Economics", units:3},
{name:"ECO25"	, desc:"Economic Research I", units:3},
{name:"ECO26"	, desc:"Economic Research II", units:3},
{name:"ECO27"	, desc:"Economic Internship", units:3},
{name:"ECO2B"	, desc:"Fiscal Studies", units:3},
{name:"ENG01"	, desc:"Basic English Language Competency", units:3},
{name:"ENG02"	, desc:"Business Communication", units:3},
{name:"ENG03"	, desc:"Speech Communications", units:3},
{name:"ENG04"	, desc:"Research Methods and Applications", units:3},
{name:"ENG06"	, desc:"Argumentation and Debate", units:3},
{name:"ENG08"	, desc:"Expository Writing", units:3},
{name:"ENG4A"	, desc:"Technical Writing in Marketing Research", units:3},
{name:"ENG4B"	, desc:"Technical Writing for Business", units:3},
{name:"ENGO2"	, desc:"Business Communication", units:3},
{name:"ENT01"	, desc:"Entrepreneurial Behavior", units:3},
{name:"ENT02"	, desc:"Business Opportunities", units:3},
{name:"ENT03"	, desc:"Business Opportunities 2", units:3},
{name:"ENT04"	, desc:"Cost Accounting", units:3},
{name:"ENT05"	, desc:"Business Plan 1", units:3},
{name:"ENT06"	, desc:"Business Plan 2", units:3},
{name:"ENT07"	, desc:"Management Accounting", units:3},
{name:"ENT08"	, desc:"Operations Research", units:3},
{name:"ENT09"	, desc:"Business Plan Implementation 1", units:3},
{name:"ENT10"	, desc:"Business Plan Implementation 2", units:3},
{name:"ENT11"	, desc:"Entrepreneurship Fora and Assimilation", units:3},
{name:"ENT12"	, desc:"Strategic Management and Business Policy", units:3},
{name:"ENTEA"	, desc:"New Market Development", units:3},
{name:"ENTEB"	, desc:"Managing the Family Firm", units:3},
{name:"ENTEC"	, desc:"Agricultural Entrepreneurship", units:3},
{name:"ENTED"	, desc:"Managing a service Enterprise", units:3},
{name:"ENTEE"	, desc:"Managing a Manufacturing Enterprise", units:3},
{name:"ENTEF"	, desc:"Export Marketing", units:3},
{name:"ENTEG"	, desc:"Capital and Securities Market", units:3},
{name:"ENTEH"	, desc:"Venture Capital", units:3},
{name:"ENVSC"	, desc:"Earth Science and the Environment", units:3},
{name:"ERTSC"	, desc:"Earth Science and the Environment", units:3},
{name:"FILI1"	, desc:"Komunikasyon sa Akademikong Filipino", units:3},
{name:"FILI2"	, desc:"Pagbasa at Pagsulat Tungo sa Pananaliksik", units:3},
{name:"FILI3"	, desc:"Masining na Pagpapahayag", units:3},
{name:"FIN01"	, desc:"Basic Finance", units:3},
{name:"FME0"	, desc:"Financial Controllership", units:3},
{name:"FME01"	, desc:"Islamic Finance", units:3},
{name:"FME02"	, desc:"Risk Management", units:3},
{name:"FME03"	, desc:"Public Finance", units:3},
{name:"FME04"	, desc:"Security Analysis", units:3},
{name:"HIS01"	, desc:"Philippine History and Culture", units:3},
{name:"HIS02"	, desc:"Society and Culture with Family Planning", units:3},
{name:"HIS03"	, desc:"Rizal’s Life and Writings", units:3},
{name:"HKD01"	, desc:"Physical Fitness Test/ Gymnastics/ Aerobics", units:3},
{name:"HKD02"	, desc:"Rhythmic Activities, Lead Up Games", units:3},
{name:"HKD03"	, desc:"Individual/ Dual Sports", units:3},
{name:"HKD04"	, desc:"Team Sports", units:3},
{name:"HMR06"	, desc:"Labor Relations and Negotiations", units:3},
{name:"HRE01"	, desc:"Managerial Accounting", units:3},
{name:"HRE02"	, desc:"Marketing Management", units:3},
{name:"HRE03"	, desc:"Entrepreneurial Management", units:3},
{name:"HRE04"	, desc:"Environmental Management", units:3},
{name:"HRE05"	, desc:"Logistics Management", units:3},
{name:"HRE06"	, desc:"Global/ International Trade", units:3},
{name:"HRE07"	, desc:"Project Management", units:3},
{name:"HRE08"	, desc:"Conflict Management", units:3},
{name:"HRE09"	, desc:"Creative Thinking", units:3},
{name:"HRM01"	, desc:"Administrative and Office Management", units:3},
{name:"HRM02"	, desc:"Recruitment and Selection", units:3},
{name:"HRM03"	, desc:"Labor Law and Legislation", units:3},
{name:"HRM04"	, desc:"Training and Development", units:3},
{name:"HRM05"	, desc:"Compensation Administration", units:3},
{name:"HRM07"	, desc:"Organizational Development", units:3},
{name:"HRM08"	, desc:"Strategic Human Resource Management", units:3},
{name:"HRM09"	, desc:"Special Topics in Human Resource Management", units:3},
{name:"HRSOP"	, desc:"Human Relations and Social Orientation Program", units:3},
{name:"HUM01"	, desc:"Art, Man, and Society", units:3},
{name:"IBE01"	, desc:"Principles of Management", units:3},
{name:"IBE02"	, desc:"Human Behavior in Business Organizations", units:3},
{name:"IBE03M"	, desc:"Human Resource Development", units:3},
{name:"IBE05"	, desc:"Business Finance and the Philippine Financial System", units:3},
{name:"IBE1B"	, desc:"Strategic Management", units:3},
{name:"ICT01"	, desc:"Information and Communications Technology Concept", units:3},
{name:"ICT02"	, desc:"Program Logic Formulation with Programming Part 1", units:3},
{name:"ICT03"	, desc:"Digital Logic Circuits", units:3},
{name:"ICT04"	, desc:"Computer Programming Part 2", units:3},
{name:"ICT05"	, desc:"Data Structures and Algorithm Analysis", units:3},
{name:"ICT06"	, desc:"Database Management System 1", units:3},
{name:"ICT07"	, desc:"Operating Systems", units:3},
{name:"ICT08"	, desc:"Database Management", units:3},
{name:"ICT09"	, desc:"Computer Graphics and Multi-media Systems", units:3},
{name:"ICT10"	, desc:"Object- Oriented Programming", units:3},
{name:"ICT11"	, desc:"Web- based Programming", units:3},
{name:"ICT12"	, desc:"Data Communication Systems", units:3},
{name:"ICT13"	, desc:"Information Resource Management", units:3},
{name:"ICT14"	, desc:"Quality Processes", units:3},
{name:"ICT15"	, desc:"Computer System Organization", units:3},
{name:"ICT16"	, desc:"Network Installation and Administration", units:3},
{name:"ICT17"	, desc:"Code of Ethics for ICT Professionals", units:3},
{name:"ICT18"	, desc:"Basic Systems Analysis and Design", units:3},
{name:"ICT19"	, desc:"Advanced Web Page Programming", units:3},
{name:"ICT20"	, desc:"Current/ Future Trends in Information and Communications Technology", units:3},
{name:"ICT21"	, desc:"Wireless Application", units:3},
{name:"ICT22"	, desc:"Advanced Systems Analysis and Design", units:3},
{name:"ICT23"	, desc:"E-commerce Technology", units:3},
{name:"ICT24"	, desc:"Research Project Proposal", units:3},
{name:"ICT25"	, desc:"Management Information Systems", units:3},
{name:"ICT26"	, desc:"Research Project Defense", units:3},
{name:"ICT27"	, desc:"Practicum", units:3},
{name:"ICT2E"	, desc:"Database with Spreadsheet", units:3},
{name:"ICT2L"	, desc:"Computer Graphics and Presentation Software", units:3},
{name:"LANG1"	, desc:"Foreign Language", units:3},
{name:"LGM01"	, desc:"Law on Persons and Family Relations", units:3},
{name:"LGM02"	, desc:"Legal Writing and Research", units:3},
{name:"LGM03"	, desc:"Law on Obligations and Contracts", units:3},
{name:"LIT01"	, desc:"Philippine Literature", units:3},
{name:"LIT02"	, desc:"World Literature", units:3},
{name:"LMG04"	, desc:"Law on Sales, Bailments and Credit Transactions", units:3},
{name:"LMG05"	, desc:"Law on Negotiable Instruments", units:3},
{name:"LMG06"	, desc:"Constitutional Law", units:3},
{name:"LMG07"	, desc:"Criminal Law", units:3},
{name:"LMG08"	, desc:"Banking and Insurance Laws", units:3},
{name:"LMG09"	, desc:"Business Organizations I (Agency and Partnership)", units:3},
{name:"LMG10"	, desc:"Business Organizations II (Corporations)", units:3},
{name:"LMG11"	, desc:"Labor Laws", units:3},
{name:"LMG13"	, desc:"Other Commercial Laws", units:3},
{name:"LMG14"	, desc:"Other Civil Laws", units:3},
{name:"LMG15"	, desc:"Income Taxation", units:3},
{name:"LMG16"	, desc:"Business Taxation", units:3},
{name:"LMG17"	, desc:"Business Forms and Procedures", units:3},
{name:"LMG18"	, desc:"Business and Legal Ethics", units:3},
{name:"MGT01"	, desc:"Principles of Management", units:3},
{name:"MGT02"	, desc:"Human Behavior in Organization", units:3},
{name:"MGT03"	, desc:"Social Responsibility and Good Governance", units:3},
{name:"MGT04 "	, desc:"Multi Cultural Human Resource Management", units:3},
{name:"MGT05"	, desc:"Production and Operations Management", units:3},
{name:"MGT05"	, desc:"Production/ Operations Management", units:3},
{name:"MGT06"	, desc:"Total Quality Management", units:3},
{name:"MGT07"	, desc:"Ethics in the Business Organization", units:3},
{name:"MGT08"	, desc:"Leadership Development", units:3},
{name:"MGT1L"	, desc:"Compensation Management", units:3},
{name:"MGT2L"	, desc:"Business Planning", units:3},
{name:"MGTO9"	, desc:"Business Policy and Strategic Management", units:3},
{name:"MKC01"	, desc:"Principles of Marketing", units:3},
{name:"MKC02"	, desc:"Consumer Behavior/Consumer Research Application", units:3},
{name:"MKC03"	, desc:"Professional Selling & Sales Management", units:3},
{name:"MKC04"	, desc:"Marketing Research", units:3},
{name:"MKC05A"	, desc:"Principles of Advertising and Sales Promotion", units:3},
{name:"MKC06A"	, desc:"Internet Marketing", units:3},
{name:"MKC07A"	, desc:"Corporate Communication Public Relations", units:3},
{name:"MKC08A"	, desc:"Distribution Management", units:3},
{name:"MKC09A"	, desc:"Strategic Marketing Management", units:3},
{name:"MKC10A"	, desc:"Retail Management", units:3},
{name:"MKC11A"	, desc:"Service Marketing", units:3},
{name:"MKC12A"	, desc:"Marketing Management", units:3},
{name:"MKC13A"	, desc:"Special Topics in Marketing Communication", units:3},
{name:"MKC14A"	, desc:"Information Marketing", units:3},
{name:"MKC15A"	, desc:"Corporate Communication Direct Marketing", units:3},
{name:"MKC18"	, desc:"Marketing Management", units:3},
{name:"MTH01"	, desc:"College Algebra", units:3},
{name:"MTH02"	, desc:"Mathematics of Investment", units:3},
{name:"MTH03"	, desc:"Mathematical Analysis", units:3},
{name:"MTH04"	, desc:"Quantitative Techniques in Business", units:3},
{name:"MTH05"	, desc:"Calculus with Analytical Geometry", units:3},
{name:"MTH06"	, desc:"Calculus", units:3},
{name:"NSTP1"	, desc:"National Service Training Program I", units:3},
{name:"NSTP2"	, desc:"National Service Training Program II", units:3},
{name:"OPE01"	, desc:"Marketing Management", units:3},
{name:"OPE02"	, desc:"Managerial Accounting", units:3},
{name:"OPE03"	, desc:"Financial Management", units:3},
{name:"OPE07"	, desc:"Environmental Management", units:3},
{name:"OPE08"	, desc:"Global/ International Trade", units:3},
{name:"OPE09"	, desc:"Enterprise Resource Planning", units:3},
{name:"OPM01"	, desc:"Operations Management", units:3},
{name:"OPM02"	, desc:"Inventory Management and Control", units:3},
{name:"OPM03"	, desc:"Logistics Management", units:3},
{name:"OPM04"	, desc:"Cost Accounting", units:3},
{name:"OPM06"	, desc:"Facilities Management", units:3},
{name:"OPM07"	, desc:"Project Management", units:3},
{name:"OPM08"	, desc:"Strategic Operations Management", units:3},
{name:"OPM09"	, desc:"Special Topics in Operations Management", units:3},
{name:"PEPBA"	, desc:"Bedan Awareness and Personality Development Program", units:3},
{name:"PHIL01"	, desc:"Introduction to Philosophy with Logic & Critical Thingking", units:3},
{name:"PHL02"	, desc:"Philosophy of the Human Person", units:3},
{name:"PHYSC"	, desc:"Physics", units:3},
{name:"POLSC"	, desc:"Introduction to Political Science with Philippine Government and Constitution", units:3},
{name:"PRACT"	, desc:"Human Resource Development Management Internship", units:3},
{name:"PRACTFM"	, desc:"Financial Management Internship", units:3},
{name:"PRACTMK"	, desc:"Internship in Marketing & Corporate Communications", units:3},
{name:"PSY01A"	, desc:"development psychology", units:3},
{name:"PSY02A"	, desc:"psychology of personality", units:3},
{name:"PSY03A"	, desc:"Psychology of Learning", units:3},
{name:"PSY04A"	, desc:"Social Psychology", units:3},
{name:"PSY05A"	, desc:"Industrial/Organization Psychology", units:3},
{name:"PSY06A"	, desc:"Physiology Psychology", units:3},
{name:"PSY07A"	, desc:"Psychological Testing 1 with Laboratory", units:3},
{name:"PSY08A"	, desc:"Psychology Testing 2", units:3},
{name:"PSY09A"	, desc:"Methods of Research", units:3},
{name:"PSY10A"	, desc:"Techniques in Counseling", units:3},
{name:"PSY11A"	, desc:"Abnormal Psychology", units:3},
{name:"PSY12A"	, desc:"Exeperimental Psychology", units:3},
{name:"PSY13A"	, desc:"Group Process", units:3},
{name:"PSY14A"	, desc:"Thesis 1", units:3},
{name:"PSY15A"	, desc:"Principles and Services of Guidance", units:3},
{name:"PSY16A"	, desc:"Elective 1", units:3},
{name:"PSY17A"	, desc:"Thesis 2", units:3},
{name:"PSY18A"	, desc:"Practicum 1", units:3},
{name:"PSY19A"	, desc:"Healthy Psychology", units:3},
{name:"PSY20A"	, desc:"Elective 2", units:3},
{name:"PSY21A"	, desc:"Clinical Psychology", units:3},
{name:"PSY22A"	, desc:"Practicum 2 (150 hours)", units:3},
{name:"PSY23A"	, desc:"History of Psychology", units:3},
{name:"PSY24A"	, desc:"Seminar in Psychology (Current Issues and Ethical Practice)", units:3},
{name:"PSYCH"	, desc:"General Psychology", units:3},
{name:"PSYS1"	, desc:"Fundamental Statistics with Computer Applications", units:3},
{name:"PSYS2"	, desc:"Advance Statistics", units:3},
{name:"RIZAL"	, desc:"Rizal’s Life & Works", units:3},
{name:"SOCAN"	, desc:"Sociology and Anthropology in the PhilippineBusiness Environment", units:3},
{name:"TAX01"	, desc:"Income Taxation", units:3},
{name:"TAX02"	, desc:"Transfer, Business and Other Taxes", units:3},
{name:"THED1"	, desc:"Introduction to Theology and Biblical Studies", units:3},
{name:"THED2"	, desc:"New Testament Studies", units:3},
{name:"THED3"	, desc:"Church, Sacraments and Family Life", units:3},
{name:"THED4"	, desc:"Contemporary Moral Theology", units:3},
{name:"THED5"	, desc:"Social Justice", units:3},
{name:"TRIGO"	, desc:"Trigonometry", units:3},
{name:"ZOO01"	, desc:"Invertibrate Psychology", units:3}
])